server:
  port: 6677

spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名称
  cloud:
    config:
      server:
        git:
          uri: git@github.com:ZhangQiQi123/config.git #GitHub上面的git仓库名字
          search-paths:
            - config  #搜索目录
      label: master    #读取分支

#服务注册金Eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka