server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        - id: payment_routh #payment_router   #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://CLOUD-PAYMENT-SERVICE   #匹配后提供服务的路由地址
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**              #断言，路径相匹配的进行路由


        - id: payment_routh2
          uri: lb://CLOUD-PAYMENT-SERVICE   #匹配后提供服务的路由地址
          #uri: http://localhost:8001
          predicates:
            - Path=/payment/lb/**
            - After=2020-05-29T20:42:19.244+08:00[Asia/Shanghai]   #在这个事件之后，访问/payment/lb/才有效果 应用在上线时间，提前上线，但不让访问
            #- Befor=2020-05-29T20:42:19.244+08:00[Asia/Shanghai]
            #- Between=2020-05-29T20:42:19.244+08:00[Asia/Shanghai],Between=2020-05-29T23:42:19.244+08:00[Asia/Shanghai]
            #- Cookie=username,zqq       #匹配路由规则，通过对应Cookie name值和正则表达式匹配，匹配通过路由执行，匹配不通过，路由不执行
            #- Header=PcOrApp, \d+  #请求头要含有X-Request-Id属性的路由，并且值为整数的正则表达式
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-width-eureka: true
      fetch-registry: try
      defaultZone: http://eureka7001.com:7001/eureka